### ISSUE TITLE
JSD() gives NaN when any probability is 0

### ISSUE THREAD

**Issue by wkc1986** [HajkD/philentropy#1]
```
> JSD(rbind(c(0.3, 0.3, 0.4), c(0.5, 0.5, 0)))
jensen-shannon 
           NaN 
```

**Comment by HajkD** [comment]
Hi @wkc1986 

Thank you so much for pointing this out to me!

I will fix this issue and will come back to you soon.

Kind regards,
Hajk

**Comment by wkc1986** [comment]
Think I fixed this in my branch by editing `jensen_shannon()` and `jensen_difference()` in `distances.h`. I'd be grateful if you could test!

**Comment by HajkD** [comment]
Sounds perfect! :D 
Thank you very much for finding the bug! 
Could you send me a pull request with your fix and then I can merge your branch.

Kind regards,
Hajk

**Comment by HajkD** [comment]
Hi @wkc1986 

Thank you so much for sending me the pull request.
I now checked your code and found the bug thanks to your code.

The problem was that in the Rcpp function `jensen_shannon()`  I was overwriting the variable `sum1` twice, e.g.:

```
if (unit == "log"){
                                        sum1  +=  P[i] * log((2.0 * P[i]) / PQsum);
                                        sum1  +=  Q[i] * log((2.0 * Q[i]) / PQsum);
                                }
```

However, it should have been:

```
if (unit == "log"){
                                        sum1  +=  P[i] * log((2.0 * P[i]) / PQsum);
                                        sum2  +=  Q[i] * log((2.0 * Q[i]) / PQsum);
                                }
```

I now fixed this issue.

In addition, I only tested the case when `P(x_i) == 0 AND Q(y_i) == 0` but not the case when `P(x_i) == 0 OR Q(y_i) == 0`. I now also fixed this issue and now implemented:

 ```
if((P[i] == 0.0) || (Q[i] == 0.0)){
                                if (P[i] == 0.0)
                                        sum1 += 0.0;
                                if (Q[i] == 0.0)
                                        sum2 += 0.0;
                        } else {
```

I also wrote new unit tests to cover and check these cases. I hope that everything works fine now and please let me know if you find any additional issues.

You helped me a lot to find this bug! Once more, thank you very very much :)

Kind regards,
Hajk

**Comment by wkc1986** [comment]
Glad to be of help! By the way, this isn’t a bug but I was wondering why you have both the `jensen_shannon()` and `jensen_difference()` implementations of the JSD? They seem to be equivalent?

**Comment by HajkD** [comment]
You are absolutely right, I think it happened due to historical reasons because I didn't have the capacity to develop this package continuously. So it might have happened that at the time I didn't see the equivalence, because in the literature sometimes you find the same formula published independently using two different names. In the future, I will try to remove one of them, but for now I stick to the rule `never touch a working system` :D 

Many thanks!
Hajk
