### ISSUE TITLE
Examples of using distance function on real data?

### ISSUE THREAD

**Issue by lwjohnst86** [HajkD/philentropy#12]
Love this package, really nicely done. However, I'm struggling to understand how to use these functions on actual real data. The documentation mentions "probability vectors" for x, but never actually shows how to use the functions on real data with real-world values. Any suggestion on how to go about converting real data to these probability vectors? And how this might change based on the distance method used?

**Comment by wkc1986** [comment]
I think for most use cases you'd want to convert the data to a count vector, where each element is the number of times the variable has that discrete value in your data set. For continuous variables you'd want to discretize it and basically make a histogram for each data set with the same bin edges. For distances that work with probabilities instead of counts, divide the count vector by the sum of all its elements so that the resultant vector sums to 1.

**Comment by HajkD** [comment]
Hi Luke,

I am very happy that you find `philentropy` useful.

I am more than happy to help you better understand how to use the package on particular types of data.

Would it be possible that you send me an example `real world` dataset that you usually work with
so that I can better construct an example that you might find useful?

Many thanks for your feedback, I truly appreciate it!

Cheers,
Hajk

**Comment by lwjohnst86** [comment]
Hey, sorry the late reply.

A fake, toy example might be where there are 2 assessments for a disease that have questions that are either binary or three levels and another assessment that uses a measure that gives a continuous value. So the toy, fake data is here:
[toy_data.txt](https://github.com/HajkD/philentropy/files/2577653/toy_data.txt)

The data has two questionnaire based assessments (`mtcss` and `tcss`) as well as one instrument-based measure (`dpn`). So this is why I was thinking of using Gower's distance since they are mixed type. 

Anyway, let me know if you have any questions about the toy data.

Thanks!

**Comment by TylerGrantSmith** [comment]
I am currently incorporating this package into a tool for monitoring SQL tables.  In particular, I want to track covariate shift which may be impacting models, and identify ETL problems that today aren't being caught until potentially months after the data is loaded.

**Comment by HajkD** [comment]
Hi all,

Sorry for my late reply and thank you so much for providing a toy example.

This will be very useful for others to learn the package as well.

Using your toy data I constructed the following example:

```r
# import toy data
toy_data <- readr::read_csv("toy_data.txt", col_names = TRUE)
# transform toy data to be conform with philentropy input format
toy_data <- t(toy_data)
# compute distance matrix using tanimoto distance
dist_matrix <- philentropy::distance(toy_data, method = "tanimoto")
# visualize output
head(dist_matrix)
```

```
#> Metric: 'tanimoto'; comparing: 32 vectors.
          v1        v2        v3        v4        v5        v6        v7        v8     v9
v1 0.0000000 0.7142857 0.6666667 0.8333333 0.7000000 0.8333333 0.7368421 0.6666667 0.6875
v2 0.7142857 0.0000000 0.6250000 1.0000000 0.6666667 0.8000000 0.7894737 0.7333333 0.7500
v3 0.6666667 0.6250000 0.0000000 0.7142857 0.5000000 0.7142857 0.6315789 0.5333333 0.5625
v4 0.8333333 1.0000000 0.7142857 0.0000000 0.7500000 0.6666667 0.8947368 0.8666667 0.8750
v5 0.7000000 0.6666667 0.5000000 0.7500000 0.0000000 0.8888889 0.5789474 0.4666667 0.5000
v6 0.8333333 0.8000000 0.7142857 0.6666667 0.8888889 0.0000000 0.8947368 0.8666667 0.8750
         v10       v11       v12       v13       v14       v15       v16       v17       v18
v1 0.7058824 0.7916667 0.7142857 0.2000000 0.5714286 0.7777778 0.5555556 0.6250000 0.8888889
v2 0.7647059 0.8333333 0.8571429 0.8571429 0.5000000 0.8888889 0.5000000 0.7500000 0.5000000
v3 0.5882353 0.7083333 0.6250000 0.6250000 0.5000000 0.5555556 0.5000000 0.3750000 0.6666667
v4 0.8823529 0.9166667 0.5000000 0.8000000 0.8333333 0.8571429 1.0000000 0.8571429 1.0000000
v5 0.5294118 0.6666667 0.6666667 0.8000000 0.7000000 0.4444444 0.4000000 0.6000000 0.3750000
v6 0.8823529 0.9166667 0.5000000 0.8000000 0.6000000 0.8571429 0.8888889 0.8571429 1.0000000
         v19       v20       v21       v22       v23       v24       v25       v26       v27
v1 0.8571429 0.3333333 0.7777778 0.4285714 0.5454545 0.6153846 0.6666667 0.6428571 0.9615951
v2 0.8333333 0.5000000 0.7500000 0.5714286 0.6363636 0.6923077 0.7333333 0.7142857 0.9692761
v3 0.5714286 0.6666667 0.3750000 0.7000000 0.3636364 0.4615385 0.5333333 0.5000000 0.9462331
v4 0.3333333 1.0000000 0.6666667 1.0000000 0.8181818 0.8461538 0.8666667 0.8571429 0.9846380
v5 0.6250000 0.7000000 0.4444444 0.6000000 0.2727273 0.3846154 0.4666667 0.4285714 0.9385522
v6 0.7500000 0.8333333 0.6666667 0.8571429 0.8181818 0.8461538 0.8666667 0.8571429 0.9846380
         v28       v29       v30       v31       v32
v1 0.9655861 0.9716234 0.9727574 0.9731439 0.9683058
v2 0.9724689 0.9772987 0.9782059 0.9785151 0.9746446
v3 0.9518206 0.9602727 0.9618604 0.9624014 0.9556281
v4 0.9862345 0.9886493 0.9891030 0.9892576 0.9873223
v5 0.9449378 0.9545974 0.9564119 0.9570302 0.9492892
v6 0.9862345 0.9886493 0.9891030 0.9892576 0.9873223
```

In the future version of `philentropy` I will also implement a new argument `use_col_names` to enable using the column names directly instead of `v_1, ..., v_N`.

Please let me know if that helps?

Kind wishes,
Hajk
