### ISSUE TITLE
About generalised Jensen Shannon Divergence (gJSD)

### ISSUE THREAD

**Issue by vrodriguezf** [HajkD/philentropy#14]
Hi,

I have two questions about the gJSD() function.

1. How does it work internally? Is there any reference that defines this measure? Is it just an aggregation?

2. Taking a look at the code of the function `gJSD()`, I can see that `nDistributions <- ncol(x)` and  `nElements <- nrow(x)`. However, the example in the function help page uses the matrix `Prob`, defined as:
```r
Prob <- rbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))
```

This matrix is a 3x10 matrix, with the distributions as rows and the elements as columns. Is this a bug? Am I missing something?

Many thanks in advance!

**Comment by HajkD** [comment]
Hi Víctor,

Many thanks for making me aware of this issue.

Regarding your first question:

>How does it work internally? Is there any reference that defines this measure? Is it just an aggregation?

Yes, I implemented this metric according to the following reference:

Lin 1991 -> https://www.cise.ufl.edu/~anand/sp06/jensen-shannon.pdf (see page 149)

Regarding your second question, I will have a look at whether or not it is a bug. It has been 3 years since I implemented this function. Thus, I need to make sure to not introduce a mistake with the assumption that it is a bug. But I will come back to you asap.

Thank you very very much for pointing this out to me :)

Best wishes,
Hajk

**Comment by vrodriguezf** [comment]
Thank you for the reference @HajkD , I look forward to your reply. You did a great job in this package!

**Comment by HajkD** [comment]
Hi Víctor,

I am very sorry that it took me so long to come back to you, but I now resolved the issue.

In the old version of `philentropy` (the one you were using) the documentation was wrong.

Instead of 

```r
Prob <- rbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))
```

it should have been

```r
Prob <- cbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))
```

Thus, I swapped `rbind()` and `cbind()`. 

However, since in all other examples of all other functions I use `rbind()` and not `cbind()` as example input, to be consistent across all functions I now implemented the function so that it takes a `rbind()` matrix/data.frame as input.

I also added a more comprehensive message system that prints out more information when using the function.

You can now run

```r
# define probability matrix
Prob <- rbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))
# compute generalized JSD
gJSD(Prob)
```

```
#> Metric: 'gJSD'; unit = 'log2'; comparing: 3 vectors (v1, ... , v3).
#> Weights: v1 = 0.333333333333333, v2 = 0.333333333333333, v3 = 0.333333333333333
[1] 0.03512892
```

As you can see, I now print out the exact number of vectors that were used to compute the `gJSD`.
In addition, I also print out the weights which by default (`weights = NULL`) are uniformly distributed.

Users can also specify non-uniformly distributed weights via:

```r
# define probability matrix
Prob <- rbind(1:10/sum(1:10), 20:29/sum(20:29), 30:39/sum(30:39))
# compute generalized JSD with custom weights
gJSD(Prob, weights = c(0.5, 0.25, 0.25))
```

```
#> Metric: 'gJSD'; unit = 'log2'; comparing: 3 vectors (v1, ... , v3).
#> Weights: v1 = 0.5, v2 = 0.25, v3 = 0.25
[1] 0.04081969
```

In the process of playing with the custom weights, I realized that I had a bug in applying the weights to the input matrix. The code used to be 

```r
WeightedProbabilityMatrix <- weights * x
```

which was intended to apply each individual weight stored in `weights` to each individual column in the probability matrix `x`. Obviously, this isn't how `R` does it, so I now changed this to:

```r
for (i in seq_len(length(weights)))
                WeightedProbabilityMatrix[ , i] <- weights[i] * x[ , i]
``` 

Now, weights are applied properly to the probability matrix. 

Thus, thank you so much for contacting me. Otherwise, I wouldn't have found this issue. 

Finally, for consistency reasons I also added a new argument `est.prob` to empirically estimate probability vectors when users specify count vectors as input and extended the examples in the documentation (see `?gJSD()`).

```r
P.count <- 1:10
Q.count <- 20:29
R.count <- 30:39
x.count <- rbind(P.count, Q.count, R.count)
gJSD(x.count, est.prob = "empirical")
```

```
#> No weights were specified ('weights = NULL'), thus equal weights for all distributions will be calculated and applied.
#> Metric: 'gJSD'; unit = 'log2'; comparing: 3 vectors (v1, ... , v3).
#> Weights: v1 = 0.333333333333333, v2 = 0.333333333333333, v3 = 0.333333333333333
[1] 0.03512892
```

I hope you find these new features useful and I will work on making the messaging system of the other functions even more clear.

I truly appreciate all your help with this.

Kind wishes,
Hajk

**Comment by vrodriguezf** [comment]
Awesome, thank you for those changes @HajkD !
