### ISSUE TITLE
NaN distance for binary vectors of 0 

### ISSUE THREAD

**Issue by JonasMandel** [HajkD/philentropy#15]
Hi,

I have encountered some (probably) unwanted behaviorofthe function distance: when computing the distance beween two vectors of 0 (in the context of binary data) with some distances adapted for binary data (e.g.Jaccard or Tanimoto), the computed value is NaN: 
```
> distance(matrix(rep(0,20),nrow = 2), method = "jaccard")
Metric: 'jaccard' using unit: 'log'.
jaccard 
    NaN
``` 

Shouldn't this distance be equal to 0 ? 

This occured in a dataset of binary data on which I want to perform hierarchical clustering, and some variables (samples, actually) only contain the value 0. A workaround would be to add +1 to the whole dataset but I am not sure whether the resulting clustering would be the same for the samples that don't contain only '0'. 

Many thanks in advance for your help !
Best, Jonas

**Comment by HajkD** [comment]
Hi Jonas,

Many thanks for contacting me and making me aware of this case.

I revisited the paper (http://csis.pace.edu/ctappert/dps/d861-12/session4-p2.pdf) I used as a reference to implement all measures and would, in this case, follow the argument raised in the technical part that
`0/0 = 0`.

>Those readers who wish to implement some
distance/similarity measures presented in this section will face
some technical problems. Table 9 identifies measures with
their caveats to implementation. While most measures can be
efficiently computed using simple vector operators, some
measures prone to the division by zero and the log of zero
cases deserve careful attention. Measures like Canberra
belong to the zero divided by zero caveat group. When the
divisor becomes zero, the dividend is always zero as well. __It
should be noted that 0/0 are treated as 0. Similarly, 0 log0 is
treated as 0 as well. For the division by zero and log of zero
group cases, the zero is replaced by a very small value.__
- Cha (2007) 

Thus, I will add this special case to the function and will come back to you soon.

I hope this helps?

Cheers,
Hajk

**Comment by HajkD** [comment]
Hi Jonas,

I now added the rule for `distance( ... , method = "jaccard")` and `distance( ... , method = "tanimoto")` that when probability vectors contain zeros then the function returns a `0` rather than `NAN`.

Please be aware that according to `Cha (2007)` (http://csis.pace.edu/ctappert/dps/d861-12/session4-p2.pdf) the Jaccard similarity (see formula `(28)`) is implemented and not the Jaccard distance. Hence, your example will now return:

```r
distance(matrix(rep(0,20), nrow = 2), method = "jaccard")
```

```
#> Metric: 'jaccard'; comparing: 2 vectors.
 jaccard 
      1 
```

As expected the __similarity__ between vectors is `1`.

__Please also note__ that `Cha (2007)` intended all measures to be implemented for probability vectors. So please be aware of the limitations when working with non-probability vectors.

For the Tanimoto distance (a.k.a Jaccard coefficient) you will now get:

```r
distance(matrix(rep(0,20), nrow = 2), method = "tanimoto")
```

```
#> Metric: 'tanimoto'; comparing: 2 vectors.
tanimoto 
       0 
```

I hope this now satisfy your application?

Many thanks for your feedback!

Kind wishes,
Hajk
