### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamGG** [HajkD/philentropy#3]
Thanks for your rich package.
I guess you might correct or explain the formula of the Gower distance.
Gower : d=1/d∗∑|Pi−Qi|
d is present in both sides.
Best.

**Comment by HajkD** [comment]
Hi @SamGG 

I am very happy to hear that you find `philentropy` useful. I hope that I can continue working on it at the end of this year :)

Thank you so much for pointing this typo out to me!

I now corrected it and write:

Gower : $d = 1/N * \sum | P_i - Q_i |$, where $N$ is the total number of elements $i$ in $P_i$ and $Q_i$

I hope this is fine now. I would be very grateful if you could point out other typos or shortcomings if you detect them so that I can improve this package.

Kind regards,
Hajk

**Comment by SamGG** [comment]
Thanks for your kind answer. I will do my best.
