### ISSUE TITLE
Performance claims in the distance vignette

### ISSUE THREAD

**Issue by kellieotto** [HajkD/philentropy#9]
This is detailed feedback for your JOSS review openjournals/joss-reviews#765.

I was able to replicate everything except the last bit using `microbenchmark` to time the different functions. The problem is with running `euclidean`. If I run the code as written I get the error

```
Error in microbenchmark(distance(x, method = "euclidean", test.na = FALSE),  : 
  could not find function "euclidean"
```

If I add `philentropy::` before the function call, I get a different error.

```
Error: 'euclidean' is not an exported object from 'namespace:philentropy'
```

**Comment by HajkD** [comment]
Dear Kellie,

I am very sorry for the confusion.  There were missing `'` in my comments (see file `src/distances.h`) so that the `roxygen` package did not automatically export my functions to the `philentropy` namespace.
Since in my developer environment, these functions were defined I could use them, so I didn't
see this issue.

Thus, all I had to do was to exchange the comments:

```r
// @export
// [[Rcpp::export]]
```

by 

```r
//' @export
// [[Rcpp::export]]
```

This way `roxygen` exported all internal metric functions to the `philentropy` namespace.
The benchmark code and example should be working now.

Please accept my apologies for the dysfunctional example.

Many thanks and kind regards,
Hajk

**Comment by kellieotto** [comment]
It works now when I install the version on GitHub. Just make sure to update the CRAN version eventually!
